### ISSUE TITLE
[FEATURE]: supra's sneller

### ISSUE THREAD

**Issue by ttv-ofzeyrox** [ShadysTestserver/development#10]
### Contact Details

quintenvdb#4688

### Voertuig model

supra2 en rmodsuprapa

### Omschrijf de bug

zou deze 2 auto's wat sneller kunnen gemaankt worden want ze zijn behoorlijk traag voor wat ze zijn

### Repro

kweet niet

### Normaal gedrag

de auto's bv 350 en 370 te late rijden

**Comment by Alem569** [comment]
Hey, we hebben gekeken naar de snelheden en gaan het nog niet aanpassen. Wij vinden dat 350 / 370 te snel is dus houden we het op de huidige snelheden.
