### ISSUE TITLE
[FEATURE]: Arcades.

### ISSUE THREAD

**Issue by JeremySmitss** [ShadysTestserver/development#11]
### Contact Details

Jeremy.#7020

### Beschrijf zo duidelijk mogelijk de feature

Misschien in een rustiger deel van de map een arcade maken. Dit voor een iets leukere toevoeging in de map, je hebt namelijk een arcade op blokkenpark, maar dat gaat waarschijnlijk keihard laggen... misschien in paleto / sandy / grapeseed een arcade hall maken waar veel te doen is. Denk aan pacman, tetris,  uno etc etc. 

### Wat lost deze feature op?

n.v.t.

**Comment by Alem569** [comment]
Bedankt voor je suggestie, we zijn hier momenteel mee bezig en je zal het binnenkort in de server zien.
