### ISSUE TITLE
[Bug]: /Wapens

### ISSUE THREAD

**Issue by MosaabDevv** [ShadysTestserver/development#12]
### Contact Details

Mosaab#7777

### Wat gebeurde er?

het pakken van wapens via /wapens en attachments enz werkt niet

### Wat hoorde er te gebeuren?

Het hoort gwn te werken xd

### Wat veroorzaakt de bug?

idk

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Alem569** [comment]
Hey, is dit bij elke wapen of sommige? Over de attachments gesproken neem ik aan dat je het F1 menu bedoeld?

**Comment by MosaabDevv** [comment]
Alleen bij het pakken van wapens / attachments adden werkt het niet. Skin / ammo pakken werkt wel.

**Comment by Alem569** [comment]
> Alleen bij het pakken van wapens / attachments adden werkt het niet. Skin / ammo pakken werkt wel.

Zou jij het eens willen proberen met het F1 Attachment menu en kijken of 't dan wel werkt? Ik ga 't vanavond even bekijken.

**Comment by Alem569** [comment]
Persoon heeft te lang niet gereageerd, niemand anders heeft het probleem.
