### ISSUE TITLE
[FEATURE]: Loadingscreen muziek

### ISSUE THREAD

**Issue by JeremySmitss** [ShadysTestserver/development#13]
### Contact Details

Jeremy.#7020

### Beschrijf zo duidelijk mogelijk de feature

Dat er een muziekje komt in het loadingscreen en die je dus ook aan / uit kan zetten.

### Wat lost deze feature op?

Naja, lekkere muziek tijdens en loaden, anders is het zo'n dooie boel

**Comment by Welseyy** [comment]
Suggesties voor muziek?

**Comment by JeremySmitss** [comment]
Ik dacht iets van grenade remix van Bruno mars, of passion fruit van drake

**Comment by Welseyy** [comment]
Gebruik spotify xd
