### ISSUE TITLE
[FEATURE]: Winkel/bankovervallen alleen zichtbaar als je in porto bent

### ISSUE THREAD

**Issue by FlopperGames** [ShadysTestserver/development#15]
### Beschrijf zo duidelijk mogelijk de feature

Vaak heb je van die personen die lekker komen maaien omdat er bijna altijd Politie/KMar naar de overval gaat. Want police job etc... Nu zou je alleen de meldingen krijgen als je in porto 110 t/m 120 zit. Veel handiger en voorkomt kloten bij overvallen.

### Wat lost deze feature op?

Er is minder gekloot bij de overvallen en kan Politie/KMar hun werk beter doen.

**Comment by Alem569** [comment]
Dit gaat helaas niet gebeuren, dit met de reden dat mensen niet altijd in de porto zitten omdat ze eventueel hoofdpijn krijgen van het massale gepraat / porto spam. Toch bedankt voor het mee denken tegen de kloters!
