### ISSUE TITLE
[FEATURE]: redzone

### ISSUE THREAD

**Issue by ilayj** [ShadysTestserver/development#16]
### Contact Details

ilay#1024

### Beschrijf zo duidelijk mogelijk de feature

hoi op dit moment als je de redzone wilt joinen moet je 15 seconden wachten en als je dood gaat moet je ook 15 seconden wachten en het zou fijn zijn als die tijd sneller gaat want je gaat ook best snel dood

### Wat lost deze feature op?

door de tijd minder te maken van 15 seconden

**Comment by Welseyy** [comment]
Deze suggestie gaat niet doorgevoerd worden, dit heeft te maken met de spawn timing en het overloaden van de redzone. Je zult dan op elkaar spawnen veel erger maken als het druk is.
