### ISSUE TITLE
[FEATURE]: EUP voor HandHaving en HandHaving voertuigen

### ISSUE THREAD

**Issue by AngerSTS** [ShadysTestserver/development#18]
### Contact Details

Bassie#3305

### Beschrijf zo duidelijk mogelijk de feature

Bassie zegt "Verbetering en leuke roleplay"

### Wat lost deze feature op?

Bassie zegt "Dat ik ook als handhaving kan gaan ipv politie, het is ook erg leuk voor live streams"

**Comment by Welseyy** [comment]
Dit is mogelijk iets wat we in de toekomst toe gaan voegen, we houden hem in gedacht maar zult een lage prioriteit blijven.

**Comment by Maxva03** [comment]
@Welseyy dit zit in mickeys, wanneer shady iets doet in de komende maanden zou hij dit evt kunnen drag en droppen

**Comment by Welseyy** [comment]
Lage prioriteit, word onthouden.
