### ISSUE TITLE
[Bug]: Paaltjes buggen / gaan niet kapot of freezen tijdens het tegenaan rijden

### ISSUE THREAD

**Issue by JeremySmitss** [ShadysTestserver/development#19]
### Contact Details

Jeremy.#7020

### Wat gebeurde er?

Je rijd je er met 20 km/h of 300 km/h tegen aan en sta je instant stil, en sommige vliegen weg een freeze random

https://cdn.discordapp.com/attachments/922848235125628929/983451739015499856/unknown.png
https://cdn.discordapp.com/attachments/922848235125628929/983451739241975869/unknown.png

### Wat hoorde er te gebeuren?

Dat ze wegvliegen en niet freezen als je er tegenaan rijd

### Wat veroorzaakt de bug?

Nu kan je auto opeens random stuk gaan.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

### Relevante log bestanden

n.v.t

**Comment by Welseyy** [comment]
Leren rijden :p
