### ISSUE TITLE
[Bug]: Je kan nu enkel met politie voertuigen geen flitsboetes krijgen.... 

### ISSUE THREAD

**Issue by JeremySmitss** [ShadysTestserver/development#22]
### Contact Details

Jeremy.#7020

### Wat gebeurde er?

je krijgt nu enkel als je in een politie voertuig zit geen flitsboetes. 

### Wat hoorde er te gebeuren?

Dat je als je enkel de job ''politie'' hebt geen flitsboetes krijg, als je in een ''dsi'' voertuig rijd, een eigen auto van jou, dan krijg je wel flitsboetes ondanks je de de politiejob hebt. Kan dit veranderd worden naar de politiejob inplaats van politie voertuigen.

### Wat veroorzaakt de bug?

Dat jij veel flitsboetes krijgt in geen politie voertuigen ondanks je wel de politiejob hebt.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

laag

**Comment by Alem569** [comment]
Dit gaat helaas niet doorgevoerd worden, ondanks dat de suggestie top is hebben wij hier wat anders voor. Wesley of ik moet even toevoegen als lightbars op een auto geplakt zijn dat je dan ook geen boetes krijgt.
