### ISSUE TITLE
[FEATURE]: /setjob2

### ISSUE THREAD

**Issue by Milansts** [ShadysTestserver/development#24]
### Beschrijf zo duidelijk mogelijk de feature

Als je nu /setjob2 doet heb je de eigenlijk niks aan want je kan er niks mee doen want je kan geen sloten open doen je kan geen /eup doen enz want bijv je hebt een offi gang job en je wilt ff als politie dat je dan niet die offi gang job weg hoeft te doen en dat maakt het ook wat handiger

### Wat lost deze feature op?

Betere en leuke speel ervaring

**Comment by Alem569** [comment]
Beste,

We gaan iit helaas niet kunnen doen omdat het anders gaat buggen als jij bijvoorbeeld een gang & policejob tegelijk hebt, met bijvoorbeeld f6 menu etc.
