### ISSUE TITLE
[FEATURE]: Jordan 4s retro toevoegen

### ISSUE THREAD

**Issue by Kondiscord** [ShadysTestserver/development#25]
### Contact Details

$ k#0009

### Beschrijf zo duidelijk mogelijk de feature

Jordan 4 University blue, Jordan 4 Lightning, Jordan 4 retro black cat, Jordan 4 retro Fire red toevoegen

### Wat lost deze feature op?

Niks het is een leuk idee

**Comment by Welseyy** [comment]
Goed idee, alleen is shady half dood. Ik geef hem het door, zit er waarschijnlijk in over 4 maanden.
