### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by Tubzzies-STS** [ShadysTestserver/development#26]
### Beschrijf zo duidelijk mogelijk de feature

Dat je via Z ook echt Shooting erbij krijgt ( Meer voor de RP beetje en gewoon voor jezelf om te kijken )

### Wat lost deze feature op?

//

**Comment by Welseyy** [comment]
Ivm de hoeveelheid aantal schietende mensen, gaan we dit voorlopig nog niet toevoegen. Word onthouden, lage prioriteit.
