### ISSUE TITLE
[FEATURE]: Lists updaten + cars fixen

### ISSUE THREAD

**Issue by Aqtivee** [ShadysTestserver/development#28]
### Contact Details

Aqtive#5530

### Beschrijf zo duidelijk mogelijk de feature

Ik wil alle lists, gratis, voor jullie fixen. Ook wil ik suggesties doen voor nieuwe auto's, snelheden van auto's enigsinds kloppend maken en in verhouding tot elkaar. (G800 gaat 500+ en een RS5 gaat 280? Niet echt goede verhouding?). Dus:

- Car-, weapon-, item-, en joblist kloppend maken met de items die in de game zitten (dus alle auto's in de game met de kloppende id's in de carlist zetten etc etc.)
- Nieuwe auto's toevoegen + slecht werkende/uitziende auto's eruit.

### Wat lost deze feature op?

Dat mensen items niet kunnen vinden, dat er minder bugged vehicle's zijn. Dat er meer variatie in auto's is. Dat mensen de auto die ze mooi vinden ook echt een beetje kunnen gebruiken ipv dat het in verhouding tot de rest bijna onbruikbaar is.

**Comment by Welseyy** [comment]
Alle voertuigen staan momenteel in de cardealer, speedlimits zijn gefixt.
