### ISSUE TITLE
[FEATURE]: Mini Ak damage.

### ISSUE THREAD

**Issue by Tubzzies-STS** [ShadysTestserver/development#32]
### Contact Details

Wesleyy#9498 + alem#1274

### Beschrijf zo duidelijk mogelijk de feature

De mini ak damage omhoog doen, Een hit doet bijna niks qua damage en als je iemand in zijn benen schiet gaat hij soms niet eens laag/naar de grond.

### Wat lost deze feature op?

Damage hoger doen.

**Comment by Welseyy** [comment]
Doorgevoerd
