### ISSUE TITLE
[FEATURE]: nieuwe ambu porto, brandweer team toevoegen, betere dsi voertuigen en misschien ook nieuwe kleding, rijkswaterstaat team toevoegen en anwb oranje lampen laten werken

### ISSUE THREAD

**Issue by 12341368** [ShadysTestserver/development#35]
### Contact Details

Bwohoho#7304 

### Beschrijf zo duidelijk mogelijk de feature

Het toevoegen van brw team en rws team zorgt ervoor dat spelers ook hier mee kennis kunnen maken. Het porto systeem van de ambu fixen kan leiden tot meer gebruik van het ambu team en anwb lampen fixen en het slepen fixen maakt deze job leuker

**Comment by Alem569** [comment]
Beste,

Kunt u wat duidelijkere informatie over de 'porto' leveren, ik begrijp niet helemaal wat je bedoeld!

**Comment by Welseyy** [comment]
Langdurig geen reactie
