### ISSUE TITLE
[FEATURE]: Wheelie motor

### ISSUE THREAD

**Issue by Tubzzies-STS** [ShadysTestserver/development#36]
### Contact Details

Wesleyy#9498 + alem#1274

### Beschrijf zo duidelijk mogelijk de feature

Een bike/wheelie motor zodat je lijpe wheelies kan doen met goeie Hendeling + Misschien trucjes erop doen. Zou een zieke toevoeging zijn en weet nu al dat veel mensen het gaan gebruiken.

### Wat lost deze feature op?

Deze bike toevoeging.

**Comment by Alem569** [comment]
Heb jij eventueel een linkje of een voorbeeld van motor waar jij aandacht? Tipje volgende keer bij Contact details je eigen discord doen.
