### ISSUE TITLE
[FEATURE]: Setjob van Karmellos terug in de game

### ISSUE THREAD

**Issue by Luchi1** [ShadysTestserver/development#40]
### Beschrijf zo duidelijk mogelijk de feature

Ik heb gemerkt dat de setjob van Karmellos niet werkt, ik heb ook gehoord dat Karmellos niet officieel is dus kan alstublieft de setjob er weer in?

### Wat lost deze feature op?

Dat mensen de setjob van Karmellos kunnen gebruiken

**Comment by Alem569** [comment]
Deze zal er weer inzitten als de gang gekocht word, anders is er een kleine mogelijkheid. Anders zijn we wel veel bezig met locaties blijven weg halen van gangs die verlopen zijn etc.
