### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by MeestroGaming** [ShadysTestserver/development#42]
### Contact Details

MeestroGaming#1588

### Kenteken van voertuig

Is er niet

### Voertuig model

Tomos + faggio2

### Omschrijf de bug

Ze kunnen autos laten ontploffen als je er tegen aan rijd + Ze kunnen niet kapot 

### Repro

Geen flauw idee

### Normaal gedrag

Dat die kapot kan gaan + Niet autos laat ontploffen.

**Comment by Welseyy** [comment]
opgelost
