### ISSUE TITLE
Telefoon werkt niet[Bug]: 

### ISSUE THREAD

**Issue by StsGideon** [ShadysTestserver/development#45]
### Contact Details

Gideon#6857

### Wat gebeurde er?

Telefoon bellen
Telefoon berichten 
Werken ingame allebij niet

### Wat hoorde er te gebeuren?

Dat je gwn kan bellen
En prive naar elkaar locas etc

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Welseyy** [comment]
Discord is een programma gebruikt om mensen met elkaar te laten communiceren.
