### ISSUE TITLE
[FEATURE]: hud

### ISSUE THREAD

**Issue by ilayj** [ShadysTestserver/development#50]
### Contact Details

ilay#1024

### Beschrijf zo duidelijk mogelijk de feature

Breng aub de nieuwe tda hud terug

### Wat lost deze feature op?

<img width="157" alt="image" src="https://user-images.githubusercontent.com/101475447/178104825-498e91f1-3a30-400b-8f94-e0a8c63b1763.png">
dit

**Comment by Alem569** [comment]
We gaan deze hud niet terug brengen, hier zitten bepaalde redenen achter.
