### ISSUE TITLE
[FEATURE]: Enkelband

### ISSUE THREAD

**Issue by IkOwenJe** [ShadysTestserver/development#51]
### Contact Details

Joker.#1570

### Beschrijf zo duidelijk mogelijk de feature

Nou het is erg leuk voor Roleplay, en het brengt meer variatie's in de roleplay scenarios, want bijv, je moet thuis blijven of je mag niet ver weg lopen, dan kunnen ze voor de roleplay bijhouden waar je bent, en het brengt ook een stukje mee van het echte leven!

### Wat lost deze feature op?

Eigenlijk helemaal niks eerlijk gezegd, ik vond het een leuke idee

**Comment by Welseyy** [comment]
nee
