### ISSUE TITLE
[EUP]: handhaving eup en voertuigen 

### ISSUE THREAD

**Issue by KayVeeAitch** [ShadysTestserver/development#52]
### Contact Details

Wesleyy#9498

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

is gewoon leuk om handhaving eup te hebben enz.

**Comment by KayVeeAitch** [comment]
doe het aub

**Comment by Welseyy** [comment]
Handhaving is mislukte politie.
