### ISSUE TITLE
Motor kan niet rijden.

### ISSUE THREAD

**Issue by FINN-RP** [ShadysTestserver/development#54]
### Contact Details

- FINN -

### Kenteken van voertuig

yzfsm 

### Voertuig model

spawnnaam=yzfsm / exacte naam=Yamaha YZ450 

### Omschrijf de bug

https://medal.tv/games/gta-v/clips/sbJu1c3k_eP_m/d13372xRIaZ9?invite=cr-MSxpNk4sNzMyMDM1OSw
Als je de motor inspawnd kan je er 20sec mee rijden en dan is de benzine al op je kan hem ook niet vol tanken.

### Repro

Je moet t/car yzfsm doen en dan een stukkie rijden de benzine is binnen 20 sec op.

### Normaal gedrag

De motor moet gewoon een tijdje kunnen rijden op een tank.

**Comment by Welseyy** [comment]
Motor is uitgame gehaald, daarnaast was je tank leeg.
