### ISSUE TITLE
[FEATURE]: stamina enzo aanpassen

### ISSUE THREAD

**Issue by jurre-s** [ShadysTestserver/development#56]
### Contact Details

jurre#0658

### Beschrijf zo duidelijk mogelijk de feature

dat je met een command je stamina en al die andere dingen die je daar hebt staan kan aanpassen met bijvoorbeeld de command 
''/setstamina id hoeveel procent'' ik weet niet of jullie dit eventueel kunnen toevoegen maar het zou wel handig zijn

### Wat lost deze feature op?

als je aan het rennen bent ofzo dat je dan altijd kan blijven rennen en dat je dan niet heel lang de de gym moet staan en inplaats van in de gym te staan kan je leuke rp neerzetten

**Comment by Welseyy** [comment]
Doorgevoerd
