### ISSUE TITLE
[FEATURE]: Delay & Kill Effect.

### ISSUE THREAD

**Issue by Tubzzies-STS** [ShadysTestserver/development#59]
### Contact Details

tubzzies#0101

### Beschrijf zo duidelijk mogelijk de feature

Haai, 
Voorstel 1: Delay, stel voor je stapt uit en je trekt een wapen dat je gelijk kan schieten en niet dat er 3 seconden delay op zit.
Voorstel 2: Kill effect, als je iemand dood maakt kan je in sommige server aanzetten dat je een kill effect krijgt. Zet je dat aan in STS gaat het automatisch van on naar off, graag dit fixen.. 

Kusjes,
Tubzzies | STS Super Mod.

### Wat lost deze feature op?

Kill effect toevoegen & Delay verminderen naar eigenlijk 0,0 seconden. <3

**Comment by Welseyy** [comment]
Nee.
