### ISSUE TITLE
[FEATURE]: STAFF SUGGESTIE: Dat staff in iedere porto kan.

### ISSUE THREAD

**Issue by AngerSTS** [ShadysTestserver/development#60]
### Contact Details

Anger.#0001

### Beschrijf zo duidelijk mogelijk de feature

Waarom? Omdat ik vaker in politie porto moet luisteren voor klooters en dan kan ik er niet in omdat ik een gang role heb.

### Wat lost deze feature op?

Dat ik klooters in de politie porto (En mogelijk ook andere porto's kan tegen gaan).

**Comment by Welseyy** [comment]
Word aan gewerkt
