### ISSUE TITLE
 [EUP] betere kmar eup en meer kledingen en meer kmar voertuigen

### ISSUE THREAD

**Issue by KayVeeAitch** [ShadysTestserver/development#62]
### Contact Details

Wesleyy#9498

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

dat er meer kmar voertuigen komen en betere kmar eup

**Comment by Stimpy1560** [comment]
hode ben je wesley XD

**Comment by Welseyy** [comment]
Er zit momenteel genoeg KMAR-kleding in, als je geobsedeerd bent met de KMAR kan je hier solliciteren: https://www.defensie.nl/organisatie/marechaussee/vacatures
