### ISSUE TITLE
[Bug]: Als ik autos koop staan ze niet in mijn garage

### ISSUE THREAD

**Issue by NuggetzR6** [ShadysTestserver/development#67]
### Contact Details

Nuggetz_R6#7281

### Wat gebeurde er?

Ik kocht een G65 en ging deze fully tunen bij een tuneshop, toen wou ik hem in mn garage zetten en stond er "kan dit voertuig niet in uw garage plaatsen". Ik dacht is wel iets eenmalig dus probeer via /cars maar dat werkte ook niet, toen dacht ik, ik dv de auto wel even en pak hem dan opnieuw maar hij stond nergens niet in de impound niet in de garage nergens. Toen kocht ik opnieuw die auto deed hetzelfde maar opnieuw hij was nergens. Ook probeerde ik dit met andere auto's maar daar ook ze staan nergens. Nu is het wel gelukt met een motor en een porsche maar dat zijn de enige waarmee het wel lukt.
![afbeelding_2022-07-24_094916968](https://user-images.githubusercontent.com/109894449/180637602-639b8567-e51b-4bc4-9963-9be928d532c1.png)

### Wat hoorde er te gebeuren?

De auto's horen mijn garage in te gaan.

### Wat veroorzaakt de bug?

Bij iedereen lukt dit buiten bij mij dus ik weet niet of het bij jullie wel werkt of niet.
Ik kocht de auto g65
Ik tunede hem
Ik wou hem in mijn garage zetten
Werkte niet
Ook als ik hem niet tune werkt het niet.

### Frequentie van de bug

Altijd

### Wat is de impact van deze bug?

hoog

**Comment by Welseyy** [comment]
Zou opgelost moeten zijn.
