### ISSUE TITLE
[SUGGESTIE]: Zou je AUB de telefoon kunnen fixen?

### ISSUE THREAD

**Issue by Noah569** [ShadysTestserver/development#68]
### Contact Details

Noahh.#3738

### Beschrijf zo duidelijk mogelijk de feature

Zou je AUB de telefoon kunnen repareren dan kunnen we terug berichten verzenden en bellen dan kaan we toch naar dat tikkeltje betere RP, MVG Noahh

### Wat lost deze feature op?

Dat we weer betere RP kunnen doen en makkelijker is om nieuwe vrienden te leren kennen en te contacteren.

**Comment by Noah569** [comment]
Kan dit gefixed worden?

**Comment by Welseyy** [comment]
Je kunt een programma genaamd discord gebruiken om te communiceren.
