### ISSUE TITLE
[EUP]: 

### ISSUE THREAD

**Issue by aminluvsrick** [ShadysTestserver/development#70]
### Contact Details

Charr#3923

### Waar bevind de issue zich?

EUP/Kleding

### Wat klopt er niet

de eup is niet zo heel erg fijn vind ik aangezien bijna elke outfits custom zijn dus kan ik weinig tot geen kleding maken het is niet zo een groot probleem maar wel een vervelende want er zijn bijvoorbeeld outfits met hood aan en hood uit (capouchon) ik vind alleen maar met hood on want degene met hood uit zijn custom meeste van die outfits glitchen hem ook vaak en zijn best lelijk mss een poll er uit gooien of mensen willen dat de eup veranderd of een poll de eup van TDA is een goeie want degene die we nu hebben is alleen maar merk kleding en geen standaard kleding
![unknown](https://user-images.githubusercontent.com/110247567/181792019-6a6ef282-a8ca-4219-b4d8-e67fae4a86a3.png)
![unknown](https://user-images.githubusercontent.com/110247567/181792142-ce05a35c-a264-4c41-bd96-eea3fa843c4e.png)

hier zie je 2 afbeeldingen de eerste is normaal en de 2de custom de 2de zou eigelijk een outfit zijn met capouchon 
de meeste outfits zijn ook van politie terwijl politie echt niet zoveel nodig heeft bijna elke outfit die ik zie staat er op de zijkant (POLITIE) 
een oplossing is dat je de standard kleding er gwn inhoudt en de custom nu is de einde bijvoorbeeld 450 mss dat het 500 wordt dat alle normale kleding er in zit en de custom

een andere oplossing is de eup van tda gebruiken

Groetjes Charr,

**Comment by aminluvsrick** [comment]
top

**Comment by Welseyy** [comment]
Vervelend, gaat niet aangepast worden.
