### ISSUE TITLE
[FEATURE]: wapens beter op rug / tda wapens op rig

### ISSUE THREAD

**Issue by weerhaak** [ShadysTestserver/development#72]
### Contact Details

Weerhaak#3321

### Beschrijf zo duidelijk mogelijk de feature

Wapens zoals shotgun en mini ak beter op de rug plaatsen bijv net zoals in tda.

### Wat lost deze feature op?

De locatie van deze wapens aanpassen

**Comment by Welseyy** [comment]
Offsets zijn laatst aangepast
