### ISSUE TITLE
Flatbed werkt niet

### ISSUE THREAD

**Issue by thomio1305** [ShadysTestserver/development#73]
### Contact Details

PINO#9584

### Kenteken van voertuig

37TVR1(is van de paint job)

### Voertuig model

flatbedp/sleepwagen (in politie auto menu)

### Omschrijf de bug

De flatbed is een sleepwagen die werkt op een bed waar je de auto op kan zetten en dat de auto dan vast staat zodat je ermee kunt gaan rijden, echter in jullie server kan niemand het bedje naar beneden zetten zodat je de auto er op kunt zetten, als je eenmaal een auto op de achter kant van de flatbed hebt staan kan je deze ook niet vast zetten.
De reden dat dit voertuig niet correct funtioneerd is omdat deze samen gaat met een plugin, deze plugin zit niet in deze server en daarom werkt dit voertuig niet. 
De desbetreffende plugin heet arrest manager, dit is een lspdfr plugin, wat betekent dat deze plugin alleen werkt in samenwerking met lspdfr, en omdat lspdfr niet in deze server zit zal de plugin niet werken (denk ik), dus het beste wat gedaan kan worden is een ander basemodel te pakken en dan een paint job voor dat basemodel te pakken. Ditzelfde geld voor de anwb flatbed (spawncode:flatbed).
Ik zou het ook vet vinden om hiermee te helpen maar als dit niet nodig is hoeft dit uiteraard niet👍.

Met vriendelijke groet,
Thomas/PINO

### Repro

In de console het volgende intypen:/car flatbedp of het voertuig pakken bij het hoofdbureau van de politie, dit voertuig heet daar sleepwagen, en dan proberen het bedje van de flatbed naar beneden te krijgen.

### Normaal gedrag

Het bedje van de flatbed hoorde naar beneden te gaan.

**Comment by Welseyy** [comment]
Wij gebruiken een ander soort plugin, waardoor je heel gemakkelijk /takelen kunt gebruiken terwijl je in een voertuig zit.
