### ISSUE TITLE
[Bug]: de deepweb/telefoon doet raar

### ISSUE THREAD

**Issue by Kd0266** [ShadysTestserver/development#75]
### Contact Details

kayden#3950

### Wat gebeurde er?

als je een locatie stuurt in de deepweb komt die niet binnen je moet hem 7x sturen ofz voordat je het ziet in de deepweb en je kan geen nummer's opslaan

### Wat hoorde er te gebeuren?

je zou maar een keer je locatie sturen en dan zou die bij iedereen binnen komen

### Wat veroorzaakt de bug?

stuur een locatie in het deepweb en je ziet de locatie dan niet, tenzij je het 5/7 keer stuurt

### Frequentie van de bug

Meerdere keren per dag

### Wat is de impact van deze bug?

hoog

**Comment by Welseyy** [comment]
Gelukkig is meta-gaming toegestaan, dus kan je met andere spelers communiceren via discord.
