### ISSUE TITLE
[FEATURE]: In het kanaal extra staan politie en criminelen rollen ze hebben vorig jaar gezegd dat criminele kanalen er aan komen maar die zijn er nog steeds niet mischien die aan maken

### ISSUE THREAD

**Issue by Porg1700** [ShadysTestserver/development#82]
### Contact Details

! Porg ! 1700#0001

### Beschrijf zo duidelijk mogelijk de feature

In het kanaal extra staan politie en criminelen rollen ze hebben vorig jaar gezegd dat criminele kanalen er aan komen maar die zijn er nog steeds niet mischien die aan maken

### Wat lost deze feature op?

Is het is gwn handig

**Comment by Maxva03** [comment]
Server bestaat nog geen jaar. Opties worden waarschijnlijk binnenkort verwijderd.
