### ISSUE TITLE
[FEATURE]: /loadout

### ISSUE THREAD

**Issue by HeavyZzOfNietDan** [ShadysTestserver/development#84]
### Contact Details

HeavyZz#5533

### Beschrijf zo duidelijk mogelijk de feature

Als je /loadout doet het brood en water weghalen. Bijna niemand gebruikt het water en brood ingame. Zo heb ik ook al gezien dat bij de /loadoutkct er geen brood en water meer bij zit dus misschien ook handig om bij de rest weg te halen!

### Wat lost deze feature op?

N.v.t.

**Comment by Welseyy** [comment]
Dan gooi je het weg.
