### ISSUE TITLE
[FEATURE]: 

### ISSUE THREAD

**Issue by LetterlijkWapenGericht** [ShadysTestserver/development#86]
### Beschrijf zo duidelijk mogelijk de feature

Greenzone HB weghalen zodat we rp kunnen zetten op hb

### Wat lost deze feature op?

Leuke rp met bijvoorbeeld uitbreken HB gijzeling etc

**Comment by Welseyy** [comment]
Dit is laatst weggeweest voor 10 minuten, en er kwamen meer dan 15 reports over spelers die aan het kloten waren op HB
