### ISSUE TITLE
[FEATURE]: Bank overvallen

### ISSUE THREAD

**Issue by xPurps** [ShadysTestserver/development#9]
### Contact Details

! Xander#5790

### Beschrijf zo duidelijk mogelijk de feature

Dat je ook kleine banken kan overvallen en niet alleen de grote bank (Die overigens niet werkt? of er heel lang over doet)

### Wat lost deze feature op?

Meer overvallen

**Comment by JeremySmitss** [comment]
Als het goed is word dit gefixt en is alem ermee bezjg
